version: "3"

services:
  api-dev:
    profiles:
      - dev
    depends_on:
      - simulation
    build:
      target: dev
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./:/api/
      - /api/node_modules/
    tty: true
    stdin_open: true

  api:
    profiles:
      - prod
    depends_on:
      - simulation
    build:
      target: prod
    environment:
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"

  simulation:
    image: mysteriouscrawler/test
    ports:
      - "3000:3000"
